---

name: Tests

on:
  push:
    branches:
      - '**'
    tags:
      - 'v*.*.*'
  pull_request:
    branches:
      - '**'

env:
  NODE_VERSION: 16
  FORCE_COLOR: 1

jobs:
  test:
    if: github.event.name == 'pull_request' || github.repository.owner != 'cardil'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        profile: ['e2e', 'unit']
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0 # fetch all branches and tags

      - uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Test
        run: |
          npm install
          JEST_PROFILE=${{ matrix.profile }} npm run ci

